In [3]:
import numpy as np

# carregando os dados com numpy
entradas = np.genfromtxt('Redes Neurais/iris.data', delimiter=',', usecols=(0, 1, 2, 3))
saidas = np.genfromtxt('Redes Neurais/iris.data', delimiter=',', usecols=(4))
print(len(entradas))
print(len(saidas))

150
150


In [5]:
"""
Iris-setosa: 0
Iris-versicolor: 1
Iris-virginica: 2
"""

# mostrando as 5 primeiras amostras qeu são Iris-setosa
print(entradas[:5])
print(saidas[:5])

print('--------------------')

# mostrando as 5 ultimas amostras que são de Iris-virginica
print(entradas[-5:])
print(saidas[-5:])

[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]]
[ 0.  0.  0.  0.  0.]
--------------------
[[ 6.7  3.   5.2  2.3]
 [ 6.3  2.5  5.   1.9]
 [ 6.5  3.   5.2  2. ]
 [ 6.2  3.4  5.4  2.3]
 [ 5.9  3.   5.1  1.8]]
[ 2.  2.  2.  2.  2.]


In [7]:
# vou utilizar 105 amostras para treino sendo 35 de cada classe
entradas_treino = np.concatenate((entradas[:35], entradas[50:85], entradas[100:135]))
saidas_treino = np.concatenate((saidas[:35], saidas[50:85], saidas[100:135]))
print(len(entradas_treino))
print(len(saidas_treino))

105
105


In [9]:
entradas_teste = np.concatenate((entradas[35:50], entradas[85:100], entradas[135:]))
saidas_teste = np.concatenate((saidas[35:50], saidas[85:100], saidas[135:]))
print(len(entradas_teste))
print(len(saidas_teste))

45
45


In [10]:
from pybrain.datasets import SupervisedDataSet
from pybrain.tools.shortcuts import buildNetwork
from pybrain.supervised import BackpropTrainer

In [11]:
treinamento = SupervisedDataSet(4, 1)
for i in range(len(entradas_treino)):
    treinamento.addSample(entradas_treino[i], saidas_treino[i])

print(len(treinamento))
print(treinamento.indim)
print(treinamento.outdim)

105
4
1


In [12]:
# construindo a rede
rede = buildNetwork(treinamento.indim, 2, treinamento.outdim, bias=True)
trainer = BackpropTrainer(rede, treinamento, learningrate=0.01, momentum=0.3)

# treinando a rede
for epoca in range(1000):
    trainer.train()

# testando a rede
teste = SupervisedDataSet(4, 1)
for i in range(len(entradas_teste)):
    teste.addSample(entradas_teste[i], saidas_teste[i])
trainer.testOnData(teste, verbose=True)


Testing on data:
('out:    ', '[0.025 ]')
('correct:', '[0     ]')
error:  0.00031659
('out:    ', '[0.02  ]')
('correct:', '[0     ]')
error:  0.00019593
('out:    ', '[0.032 ]')
('correct:', '[0     ]')
error:  0.00052809
('out:    ', '[0.038 ]')
('correct:', '[0     ]')
error:  0.00071915
('out:    ', '[0.028 ]')
('correct:', '[0     ]')
error:  0.00039870
('out:    ', '[0.026 ]')
('correct:', '[0     ]')
error:  0.00032901
('out:    ', '[0.069 ]')
('correct:', '[0     ]')
error:  0.00240319
('out:    ', '[0.033 ]')
('correct:', '[0     ]')
error:  0.00053908
('out:    ', '[0.05  ]')
('correct:', '[0     ]')
error:  0.00125148
('out:    ', '[0.038 ]')
('correct:', '[0     ]')
error:  0.00073002
('out:    ', '[0.043 ]')
('correct:', '[0     ]')
error:  0.00092532
('out:    ', '[0.023 ]')
('correct:', '[0     ]')
error:  0.00026352
('out:    ', '[0.034 ]')
('correct:', '[0     ]')
error:  0.00058448
('out:    ', '[0.022 ]')
('correct:', '[0     ]')
error:  0.00023259
('out:    ', '[0

0.011528470102418987

In [13]:
rede = buildNetwork(treinamento.indim, 2, treinamento.outdim, bias=True)
trainer = BackpropTrainer(rede, treinamento, learningrate=0.01, momentum=0.5)

# treinando a rede
for epoca in range(1000):
    trainer.train()

# testando a rede
teste = SupervisedDataSet(4, 1)
for i in range(len(entradas_teste)):
    teste.addSample(entradas_teste[i], saidas_teste[i])
trainer.testOnData(teste, verbose=True)


Testing on data:
('out:    ', '[0.014 ]')
('correct:', '[0     ]')
error:  0.00009394
('out:    ', '[0.01  ]')
('correct:', '[0     ]')
error:  0.00004524
('out:    ', '[0.019 ]')
('correct:', '[0     ]')
error:  0.00017769
('out:    ', '[0.023 ]')
('correct:', '[0     ]')
error:  0.00025836
('out:    ', '[0.015 ]')
('correct:', '[0     ]')
error:  0.00011381
('out:    ', '[0.013 ]')
('correct:', '[0     ]')
error:  0.00008508
('out:    ', '[0.057 ]')
('correct:', '[0     ]')
error:  0.00162470
('out:    ', '[0.018 ]')
('correct:', '[0     ]')
error:  0.00015976
('out:    ', '[0.03  ]')
('correct:', '[0     ]')
error:  0.00046049
('out:    ', '[0.021 ]')
('correct:', '[0     ]')
error:  0.00021676
('out:    ', '[0.027 ]')
('correct:', '[0     ]')
error:  0.00037288
('out:    ', '[0.011 ]')
('correct:', '[0     ]')
error:  0.00005705
('out:    ', '[0.019 ]')
('correct:', '[0     ]')
error:  0.00018759
('out:    ', '[0.01  ]')
('correct:', '[0     ]')
error:  0.00005086
('out:    ', '[0

0.011599608333860778

In [16]:
rede = buildNetwork(treinamento.indim, 2, treinamento.outdim, bias=True)
trainer = BackpropTrainer(rede, treinamento, learningrate=0.005, momentum=0.5)

# treinando a rede
for epoca in range(2000):
    trainer.train()

# testando a rede
teste = SupervisedDataSet(4, 1)
for i in range(len(entradas_teste)):
    teste.addSample(entradas_teste[i], saidas_teste[i])
trainer.testOnData(teste, verbose=True)


Testing on data:
('out:    ', '[0.031 ]')
('correct:', '[0     ]')
error:  0.00049311
('out:    ', '[0.024 ]')
('correct:', '[0     ]')
error:  0.00028808
('out:    ', '[0.039 ]')
('correct:', '[0     ]')
error:  0.00075926
('out:    ', '[0.046 ]')
('correct:', '[0     ]')
error:  0.00107605
('out:    ', '[0.033 ]')
('correct:', '[0     ]')
error:  0.00055671
('out:    ', '[0.031 ]')
('correct:', '[0     ]')
error:  0.00047083
('out:    ', '[0.089 ]')
('correct:', '[0     ]')
error:  0.00395041
('out:    ', '[0.04  ]')
('correct:', '[0     ]')
error:  0.00079461
('out:    ', '[0.057 ]')
('correct:', '[0     ]')
error:  0.00162386
('out:    ', '[0.044 ]')
('correct:', '[0     ]')
error:  0.00094644
('out:    ', '[0.051 ]')
('correct:', '[0     ]')
error:  0.00131757
('out:    ', '[0.027 ]')
('correct:', '[0     ]')
error:  0.00036016
('out:    ', '[0.041 ]')
('correct:', '[0     ]')
error:  0.00083638
('out:    ', '[0.025 ]')
('correct:', '[0     ]')
error:  0.00032247
('out:    ', '[0

0.010868260673830175

In [18]:
rede = buildNetwork(treinamento.indim, 2, treinamento.outdim, bias=True)
trainer = BackpropTrainer(rede, treinamento, learningrate=0.3, momentum=0.9)

# treinando a rede
for epoca in range(10000):
    trainer.train()

# testando a rede
teste = SupervisedDataSet(4, 1)
for i in range(len(entradas_teste)):
    teste.addSample(entradas_teste[i], saidas_teste[i])
trainer.testOnData(teste, verbose=True)


Testing on data:
('out:    ', '[0.389 ]')
('correct:', '[0     ]')
error:  0.07572183
('out:    ', '[0.389 ]')
('correct:', '[0     ]')
error:  0.07572183
('out:    ', '[0.389 ]')
('correct:', '[0     ]')
error:  0.07572183
('out:    ', '[0.389 ]')
('correct:', '[0     ]')
error:  0.07572183
('out:    ', '[0.389 ]')
('correct:', '[0     ]')
error:  0.07572183
('out:    ', '[0.389 ]')
('correct:', '[0     ]')
error:  0.07572183
('out:    ', '[0.389 ]')
('correct:', '[0     ]')
error:  0.07572183
('out:    ', '[0.389 ]')
('correct:', '[0     ]')
error:  0.07572183
('out:    ', '[0.389 ]')
('correct:', '[0     ]')
error:  0.07572183
('out:    ', '[0.389 ]')
('correct:', '[0     ]')
error:  0.07572183
('out:    ', '[0.389 ]')
('correct:', '[0     ]')
error:  0.07572183
('out:    ', '[0.389 ]')
('correct:', '[0     ]')
error:  0.07572183
('out:    ', '[0.389 ]')
('correct:', '[0     ]')
error:  0.07572183
('out:    ', '[0.389 ]')
('correct:', '[0     ]')
error:  0.07572183
('out:    ', '[0

0.51989753482492185

In [20]:
rede = buildNetwork(treinamento.indim, 2, treinamento.outdim, bias=True)
trainer = BackpropTrainer(rede, treinamento, learningrate=0.005, momentum=0.5)

# treinando a rede
trainer.trainUntilConvergence()

# testando a rede
teste = SupervisedDataSet(4, 1)
for i in range(len(entradas_teste)):
    teste.addSample(entradas_teste[i], saidas_teste[i])
trainer.testOnData(teste, verbose=True)


Testing on data:
('out:    ', '[-0.049]')
('correct:', '[0     ]')
error:  0.00121171
('out:    ', '[-0.082]')
('correct:', '[0     ]')
error:  0.00335299
('out:    ', '[-0.012]')
('correct:', '[0     ]')
error:  0.00007600
('out:    ', '[0.027 ]')
('correct:', '[0     ]')
error:  0.00035814
('out:    ', '[-0.032]')
('correct:', '[0     ]')
error:  0.00052175
('out:    ', '[-0.041]')
('correct:', '[0     ]')
error:  0.00084817
('out:    ', '[0.075 ]')
('correct:', '[0     ]')
error:  0.00277864
('out:    ', '[0.015 ]')
('correct:', '[0     ]')
error:  0.00011885
('out:    ', '[0.034 ]')
('correct:', '[0     ]')
error:  0.00057533
('out:    ', '[0.025 ]')
('correct:', '[0     ]')
error:  0.00030818
('out:    ', '[0.013 ]')
('correct:', '[0     ]')
error:  0.00008251
('out:    ', '[-0.038]')
('correct:', '[0     ]')
error:  0.00071668
('out:    ', '[0.01  ]')
('correct:', '[0     ]')
error:  0.00004589
('out:    ', '[-0.059]')
('correct:', '[0     ]')
error:  0.00172695
('out:    ', '[-

0.013901635157587819

In [21]:
rede = buildNetwork(treinamento.indim, 2, treinamento.outdim, bias=True)
trainer = BackpropTrainer(rede, treinamento, learningrate=0.01, momentum=0.7)

# treinando a rede
for epoca in range(1000):
    trainer.train()

# testando a rede
teste = SupervisedDataSet(4, 1)
for i in range(len(entradas_teste)):
    teste.addSample(entradas_teste[i], saidas_teste[i])
trainer.testOnData(teste, verbose=True)


Testing on data:
('out:    ', '[-0.04 ]')
('correct:', '[0     ]')
error:  0.00078093
('out:    ', '[-0.058]')
('correct:', '[0     ]')
error:  0.00168326
('out:    ', '[-0.025]')
('correct:', '[0     ]')
error:  0.00030937
('out:    ', '[0.012 ]')
('correct:', '[0     ]')
error:  0.00006765
('out:    ', '[-0.015]')
('correct:', '[0     ]')
error:  0.00010724
('out:    ', '[-0.006]')
('correct:', '[0     ]')
error:  0.00001539
('out:    ', '[0.024 ]')
('correct:', '[0     ]')
error:  0.00028141
('out:    ', '[0.014 ]')
('correct:', '[0     ]')
error:  0.00009356
('out:    ', '[0.115 ]')
('correct:', '[0     ]')
error:  0.00660635
('out:    ', '[0.092 ]')
('correct:', '[0     ]')
error:  0.00423920
('out:    ', '[0.016 ]')
('correct:', '[0     ]')
error:  0.00012743
('out:    ', '[0.001 ]')
('correct:', '[0     ]')
error:  0.00000013
('out:    ', '[0.01  ]')
('correct:', '[0     ]')
error:  0.00004574
('out:    ', '[-0.025]')
('correct:', '[0     ]')
error:  0.00032258
('out:    ', '[-

0.011588878170883467