## Dataset: https://archive.ics.uci.edu/ml/datasets/Balance+Scale

###Atribute Information:

1. Class Name: 3 (L, B, R) 
2. Left-Weight: 5 (1, 2, 3, 4, 5) 
3. Left-Distance: 5 (1, 2, 3, 4, 5) 
4. Right-Weight: 5 (1, 2, 3, 4, 5) 
5. Right-Distance: 5 (1, 2, 3, 4, 5)

São 625 exemplos, 4 atributos e 3 possíveis classes.
Onde tem "L" coloquei 1, onde tem "B" coloquei 2, e onde tem "R" coloquei 3

In [1]:
import numpy as np

In [8]:
# x são entradas e y as saídas
x = np.genfromtxt(
    'E:/thcborges/OneDrive/Cursos/Udemy/machine-learning/kNN/balance-scale.data',
    delimiter=',',
    usecols=(1,2,3,4)
)
y = np.genfromtxt(
    'E:/thcborges/OneDrive/Cursos/Udemy/machine-learning/kNN/balance-scale.data',
    delimiter=',',
    usecols=(0)
)
print(len(x))
print(len(y))
print(x)
print(y)

625
625
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  2.]
 [ 1.  1.  1.  3.]
 ..., 
 [ 5.  5.  5.  3.]
 [ 5.  5.  5.  4.]
 [ 5.  5.  5.  5.]]
[ 2.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.
  3.  3.  3.  3.  3.  3.  3.  1.  2.  3.  3.  3.  2.  3.  3.  3.  3.  3.
  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  1.  1.  2.  3.
  3.  1.  3.  3.  3.  3.  2.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.
  3.  3.  3.  1.  1.  1.  2.  3.  1.  2.  3.  3.  3.  1.  3.  3.  3.  3.
  2.  3.  3.  3.  3.  3.  3.  3.  3.  3.  1.  1.  1.  1.  2.  1.  1.  3.
  3.  3.  1.  3.  3.  3.  3.  1.  3.  3.  3.  3.  2.  3.  3.  3.  3.  1.
  2.  3.  3.  3.  2.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.
  3.  3.  3.  3.  3.  3.  1.  1.  1.  2.  3.  1.  2.  3.  3.  3.  1.  3.
  3.  3.  3.  2.  3.  3.  3.  3.  3.  3.  3.  3.  3.  1.  1.  1.  1.  1.
  1.  1.  2.  3.  3.  1.  2.  3.  3.  3.  1.  3.  3.  3.  3.  1.  3.  3.
  3.  3.  1.  1.  1.  1.  1.  1.  1.  1.  2.  3.  1.  1.  3.  3.  3

In [10]:
from sklearn.cross_validation import train_test_split

doc: http://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html

In [14]:
x_treino, x_teste, y_treino, y_teste = train_test_split(x, y, test_size=0.3, random_state=42)

In [12]:
print(len(x_treino))
print(x_treino)
print(len(x_teste))
print(x_teste)

437
[[ 2.  4.  1.  5.]
 [ 1.  4.  3.  4.]
 [ 5.  1.  5.  3.]
 ..., 
 [ 3.  1.  5.  1.]
 [ 4.  3.  3.  1.]
 [ 1.  5.  1.  3.]]
188
[[ 4.  3.  5.  3.]
 [ 4.  5.  3.  1.]
 [ 2.  4.  4.  1.]
 [ 2.  4.  3.  3.]
 [ 4.  5.  2.  1.]
 [ 5.  1.  4.  1.]
 [ 2.  2.  3.  4.]
 [ 1.  4.  1.  3.]
 [ 5.  2.  1.  3.]
 [ 2.  1.  5.  1.]
 [ 3.  1.  4.  1.]
 [ 1.  2.  2.  2.]
 [ 1.  3.  2.  1.]
 [ 1.  4.  4.  1.]
 [ 5.  3.  2.  3.]
 [ 1.  4.  1.  2.]
 [ 1.  1.  1.  3.]
 [ 3.  5.  4.  4.]
 [ 4.  1.  5.  1.]
 [ 3.  2.  3.  2.]
 [ 2.  1.  2.  2.]
 [ 2.  1.  5.  4.]
 [ 1.  2.  5.  5.]
 [ 5.  5.  5.  2.]
 [ 4.  3.  3.  3.]
 [ 1.  5.  3.  1.]
 [ 3.  1.  2.  3.]
 [ 5.  4.  1.  4.]
 [ 5.  5.  5.  1.]
 [ 3.  1.  2.  2.]
 [ 3.  4.  2.  5.]
 [ 3.  1.  3.  2.]
 [ 2.  3.  2.  5.]
 [ 5.  3.  1.  5.]
 [ 2.  1.  2.  3.]
 [ 4.  5.  3.  3.]
 [ 3.  4.  3.  1.]
 [ 5.  5.  3.  3.]
 [ 2.  3.  2.  2.]
 [ 5.  4.  5.  5.]
 [ 4.  1.  2.  2.]
 [ 1.  2.  3.  5.]
 [ 1.  4.  3.  2.]
 [ 5.  5.  2.  4.]
 [ 3.  3.  4.  4.]
 [ 2.  4.  2.  

In [13]:
y_teste[0]

3.0

In [15]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=17, p=2)
knn.fit(x_treino, y_treino)
labels = knn.predict(x_teste)
print(len(labels))
print(labels)

188
[ 1.  1.  1.  1.  1.  1.  3.  1.  1.  3.  3.  3.  1.  3.  1.  1.  3.  3.
  3.  1.  3.  3.  3.  1.  1.  1.  3.  1.  1.  1.  1.  3.  3.  1.  3.  1.
  1.  1.  1.  1.  1.  3.  1.  1.  3.  1.  1.  3.  1.  3.  1.  1.  3.  3.
  1.  1.  3.  1.  1.  1.  1.  1.  3.  3.  1.  1.  3.  3.  1.  1.  3.  3.
  3.  3.  3.  1.  1.  3.  1.  3.  3.  3.  3.  1.  3.  1.  1.  1.  3.  1.
  1.  1.  3.  1.  1.  3.  3.  3.  3.  3.  1.  3.  3.  3.  1.  1.  1.  3.
  3.  1.  3.  1.  3.  3.  1.  3.  1.  1.  1.  1.  3.  3.  1.  3.  3.  3.
  3.  3.  1.  3.  1.  1.  1.  3.  1.  1.  1.  3.  1.  1.  1.  1.  3.  3.
  1.  3.  3.  1.  3.  3.  3.  3.  3.  1.  1.  3.  1.  1.  3.  1.  1.  3.
  3.  1.  1.  1.  3.  1.  3.  3.  1.  3.  3.  3.  1.  1.  1.  1.  3.  1.
  3.  3.  1.  3.  3.  3.  3.  1.]


In [16]:
print(y_teste)

[ 3.  1.  1.  3.  1.  1.  3.  1.  1.  3.  3.  3.  1.  2.  1.  1.  3.  3.
  3.  2.  3.  3.  3.  1.  1.  1.  3.  1.  1.  3.  1.  3.  3.  1.  3.  1.
  1.  1.  1.  3.  2.  3.  3.  1.  3.  2.  2.  3.  2.  3.  1.  1.  3.  3.
  1.  1.  3.  1.  1.  2.  1.  1.  3.  3.  1.  1.  3.  3.  1.  1.  3.  3.
  3.  3.  3.  1.  1.  3.  1.  3.  3.  2.  3.  1.  3.  2.  1.  1.  3.  1.
  1.  1.  3.  1.  1.  3.  3.  3.  3.  3.  1.  2.  3.  3.  1.  2.  1.  3.
  3.  1.  3.  1.  3.  3.  1.  3.  1.  1.  1.  1.  3.  3.  1.  3.  3.  3.
  3.  3.  2.  3.  1.  1.  2.  3.  1.  1.  1.  3.  1.  1.  1.  3.  3.  3.
  1.  3.  3.  1.  3.  3.  3.  3.  3.  1.  3.  3.  2.  1.  2.  1.  1.  3.
  3.  1.  1.  1.  3.  1.  3.  2.  1.  3.  3.  3.  2.  1.  1.  1.  3.  1.
  3.  2.  1.  3.  3.  3.  3.  1.]


In [17]:
np.sum(labels == y_teste)

163

In [18]:
(labels == y_teste).sum()

163

In [19]:
100 * np.sum(labels == y_teste) / len(x_teste)

86.702127659574472

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
knn = KNeighborsClassifier(n_neighbors=17, p=2)
knn.fit(x_treino, y_treino)
labels = knn.predict(x_teste)
print(len(labels))
print(labels)

188
[ 1.  1.  1.  1.  1.  1.  3.  1.  1.  3.  3.  3.  1.  3.  1.  1.  3.  3.
  3.  1.  3.  3.  3.  1.  1.  1.  3.  1.  1.  1.  1.  3.  3.  1.  3.  1.
  1.  1.  1.  1.  1.  3.  1.  1.  3.  1.  1.  3.  1.  3.  1.  1.  3.  3.
  1.  1.  3.  1.  1.  1.  1.  1.  3.  3.  1.  1.  3.  3.  1.  1.  3.  3.
  3.  3.  3.  1.  1.  3.  1.  3.  3.  3.  3.  1.  3.  1.  1.  1.  3.  1.
  1.  1.  3.  1.  1.  3.  3.  3.  3.  3.  1.  3.  3.  3.  1.  1.  1.  3.
  3.  1.  3.  1.  3.  3.  1.  3.  1.  1.  1.  1.  3.  3.  1.  3.  3.  3.
  3.  3.  1.  3.  1.  1.  1.  3.  1.  1.  1.  3.  1.  1.  1.  1.  3.  3.
  1.  3.  3.  1.  3.  3.  3.  3.  3.  1.  1.  3.  1.  1.  3.  1.  1.  3.
  3.  1.  1.  1.  3.  1.  3.  3.  1.  3.  3.  3.  1.  1.  1.  1.  3.  1.
  3.  3.  1.  3.  3.  3.  3.  1.]


In [22]:
knn.score(x_teste, y_teste) * 100

86.702127659574472

In [24]:
np.mean(labels == y_teste) * 100

86.702127659574472