In [1]:
import numpy as np

In [3]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
np.array_split(a, 2, axis=0)

[array([[1, 2, 3]]), array([[4, 5, 6]])]

In [7]:
np.array_split(a, 2, axis=0)

[array([[1, 2, 3]]), array([[4, 5, 6]])]

In [9]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [10]:
arrays = np.array_split(b, 2, axis=0)
for array in arrays:
    print(array)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
