In [1]:
import numpy

In [2]:
a = numpy.array([10, 20, 30, 40])
a

array([10, 20, 30, 40])

In [3]:
type(a)

numpy.ndarray

In [4]:
mat = numpy.array([[1, 2],
                   [3, 4]])
mat

array([[1, 2],
       [3, 4]])

In [5]:
print(mat[1][1])
print(mat[-1][-1])

4
4


In [6]:
mat[1,:]

array([3, 4])

In [7]:
mat[:, 0]

array([1, 3])

In [8]:
mat.transpose()

array([[1, 3],
       [2, 4]])

In [10]:
m1 = numpy.array([[1, 2], [3, 4]])
m2 = numpy.array([[5, 6], [7, 8]])
m1 + m2

array([[ 6,  8],
       [10, 12]])

In [11]:
m1 - m2

array([[-4, -4],
       [-4, -4]])

In [12]:
m1 * m2

array([[ 5, 12],
       [21, 32]])

In [14]:
m3 = numpy.array([1, 2, 3, 4])
m3.sum()

10

In [15]:
m3.argmax()

3

In [16]:
m3.argmin()

0

In [18]:
import numpy as np


a = np.array([[2, 4],
              [6, 8]])
print(a.mean())
print(a.diagonal())
print(a.ndim)

5.0
[2 8]
2


In [20]:
lista = [1, 2, 3, 'Thiago']
lista.

[1, 2, 3, 'Thiago']

In [31]:
%%time
soma = 0
for i in range(1, 100000001):
    soma += i
print(soma)

5000000050000000
Wall time: 11.6 s


In [30]:
%%time
np.arange(1, 100000001, dtype='int64').sum()

Wall time: 406 ms


5000000050000000

In [35]:
l = [ 20, 30, 10, 40]
print(l[1:3])
print(l[::2])

[30, 10]
[20, 10]


In [36]:
import numpy as np


a = np.array(l)
a

array([20, 30, 10, 40])

In [37]:
print(a[1:3])
print(a[::2])

[30 10]
[20 10]


In [38]:
l2 = l[:]
l2

[20, 30, 10, 40]

In [39]:
l2[0] = 1000
print(l)
print(l2)

[20, 30, 10, 40]
[1000, 30, 10, 40]


In [41]:
b = a[:]

In [42]:
b[0] = 1000
print(a)
print(b)

[1000   30   10   40]
[1000   30   10   40]


In [43]:
b[:] = 42
a

array([42, 42, 42, 42])

In [44]:
c = a.copy()
print(c)
print(a)

[42 42 42 42]
[42 42 42 42]


In [45]:
c[0] = 1000000
print(c)
print(a)

[1000000      42      42      42]
[42 42 42 42]


In [2]:
mat = [[5, 4, 7], [0, 3, 4], [0, 0, 6]]
for linha in mat:
    print(linha)

[5, 4, 7]
[0, 3, 4]
[0, 0, 6]


In [3]:
import numpy as np

In [5]:
joao_pts = [20, 30, 40, 15]
pedro_pts = [100, 24, 48, 23]
maria_pts = [92, 22, 34, 12]
marcos_pts = [12, 34, 12, 43]

pontos = np.array([joao_pts, pedro_pts, maria_pts, marcos_pts])

In [6]:
pontos

array([[ 20,  30,  40,  15],
       [100,  24,  48,  23],
       [ 92,  22,  34,  12],
       [ 12,  34,  12,  43]])

In [7]:
pontos[0]

array([20, 30, 40, 15])

In [8]:
pontos[1][0]

100

In [10]:
my_data = np.arange(0, 20)
print(my_data)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [13]:
mat1 = np.reshape(my_data, (5, 4))
print(mat1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [15]:
mat1[2,2]

10

In [17]:
pontos.item(5)

24

In [18]:
m1 = ['python', 'eh', 'legal']
m2 = ['guido', 'van', 'rossum']
m3 = [10, 20, 30]


In [20]:
[m1, m2, m3]

[['python', 'eh', 'legal'], ['guido', 'van', 'rossum'], [10, 20, 30]]

In [22]:
np.array([m1, m2, m3])

array([['python', 'eh', 'legal'],
       ['guido', 'van', 'rossum'],
       ['10', '20', '30']],
      dtype='<U6')

In [23]:
m1 = np.array([[1,2,3], [4,5,6]])
m2 = np.array([[7,8,9], [10,11,12]])

In [24]:
m1

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
m2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [26]:
m2 / m1

array([[ 7. ,  4. ,  3. ],
       [ 2.5,  2.2,  2. ]])

In [27]:
np.matrix.round(m2 / m1)

array([[ 7.,  4.,  3.],
       [ 2.,  2.,  2.]])

In [28]:
10 * m2

array([[ 70,  80,  90],
       [100, 110, 120]])

In [29]:
m1 + 5

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [30]:
m2 - 1

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [31]:
m1 * m2

array([[ 7, 16, 27],
       [40, 55, 72]])

In [32]:
m1 ** 2

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

In [33]:
import matplotlib.pylot as plt

ModuleNotFoundError: No module named 'matplotlib.pylot'